//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoPeru.ProxyEmpleado {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpleadoBE", Namespace="http://schemas.datacontract.org/2004/07/ServiciosBancoPeru")]
    [System.SerializableAttribute()]
    public partial class EmpleadoBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ape_EmpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float Cod_DepaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float Cod_EmpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dir_EmpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dni_EmpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Email_EmpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_IngField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_EmpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SucursalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float Sue_EmpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tel_EmpField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_Emp {
            get {
                return this.Ape_EmpField;
            }
            set {
                if ((object.ReferenceEquals(this.Ape_EmpField, value) != true)) {
                    this.Ape_EmpField = value;
                    this.RaisePropertyChanged("Ape_Emp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Cod_Depa {
            get {
                return this.Cod_DepaField;
            }
            set {
                if ((this.Cod_DepaField.Equals(value) != true)) {
                    this.Cod_DepaField = value;
                    this.RaisePropertyChanged("Cod_Depa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Cod_Emp {
            get {
                return this.Cod_EmpField;
            }
            set {
                if ((this.Cod_EmpField.Equals(value) != true)) {
                    this.Cod_EmpField = value;
                    this.RaisePropertyChanged("Cod_Emp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dir_Emp {
            get {
                return this.Dir_EmpField;
            }
            set {
                if ((object.ReferenceEquals(this.Dir_EmpField, value) != true)) {
                    this.Dir_EmpField = value;
                    this.RaisePropertyChanged("Dir_Emp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dni_Emp {
            get {
                return this.Dni_EmpField;
            }
            set {
                if ((object.ReferenceEquals(this.Dni_EmpField, value) != true)) {
                    this.Dni_EmpField = value;
                    this.RaisePropertyChanged("Dni_Emp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email_Emp {
            get {
                return this.Email_EmpField;
            }
            set {
                if ((object.ReferenceEquals(this.Email_EmpField, value) != true)) {
                    this.Email_EmpField = value;
                    this.RaisePropertyChanged("Email_Emp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Ing {
            get {
                return this.Fec_IngField;
            }
            set {
                if ((this.Fec_IngField.Equals(value) != true)) {
                    this.Fec_IngField = value;
                    this.RaisePropertyChanged("Fec_Ing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Emp {
            get {
                return this.Nom_EmpField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_EmpField, value) != true)) {
                    this.Nom_EmpField = value;
                    this.RaisePropertyChanged("Nom_Emp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sucursal {
            get {
                return this.SucursalField;
            }
            set {
                if ((object.ReferenceEquals(this.SucursalField, value) != true)) {
                    this.SucursalField = value;
                    this.RaisePropertyChanged("Sucursal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Sue_Emp {
            get {
                return this.Sue_EmpField;
            }
            set {
                if ((this.Sue_EmpField.Equals(value) != true)) {
                    this.Sue_EmpField = value;
                    this.RaisePropertyChanged("Sue_Emp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel_Emp {
            get {
                return this.Tel_EmpField;
            }
            set {
                if ((object.ReferenceEquals(this.Tel_EmpField, value) != true)) {
                    this.Tel_EmpField = value;
                    this.RaisePropertyChanged("Tel_Emp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyEmpleado.IServiciosEmpleado")]
    public interface IServiciosEmpleado {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosEmpleado/InsertEmpleado", ReplyAction="http://tempuri.org/IServiciosEmpleado/InsertEmpleadoResponse")]
        bool InsertEmpleado(BancoPeru.ProxyEmpleado.EmpleadoBE objCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosEmpleado/InsertEmpleado", ReplyAction="http://tempuri.org/IServiciosEmpleado/InsertEmpleadoResponse")]
        System.Threading.Tasks.Task<bool> InsertEmpleadoAsync(BancoPeru.ProxyEmpleado.EmpleadoBE objCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosEmpleado/GetAllEmpleadoLINQ", ReplyAction="http://tempuri.org/IServiciosEmpleado/GetAllEmpleadoLINQResponse")]
        BancoPeru.ProxyEmpleado.EmpleadoBE[] GetAllEmpleadoLINQ();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosEmpleado/GetAllEmpleadoLINQ", ReplyAction="http://tempuri.org/IServiciosEmpleado/GetAllEmpleadoLINQResponse")]
        System.Threading.Tasks.Task<BancoPeru.ProxyEmpleado.EmpleadoBE[]> GetAllEmpleadoLINQAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosEmpleado/ListarNombresEmpleadoLINQ", ReplyAction="http://tempuri.org/IServiciosEmpleado/ListarNombresEmpleadoLINQResponse")]
        BancoPeru.ProxyEmpleado.EmpleadoBE[] ListarNombresEmpleadoLINQ();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosEmpleado/ListarNombresEmpleadoLINQ", ReplyAction="http://tempuri.org/IServiciosEmpleado/ListarNombresEmpleadoLINQResponse")]
        System.Threading.Tasks.Task<BancoPeru.ProxyEmpleado.EmpleadoBE[]> ListarNombresEmpleadoLINQAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosEmpleado/GetClienteSucursal", ReplyAction="http://tempuri.org/IServiciosEmpleado/GetClienteSucursalResponse")]
        BancoPeru.ProxyEmpleado.EmpleadoBE[] GetClienteSucursal(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosEmpleado/GetClienteSucursal", ReplyAction="http://tempuri.org/IServiciosEmpleado/GetClienteSucursalResponse")]
        System.Threading.Tasks.Task<BancoPeru.ProxyEmpleado.EmpleadoBE[]> GetClienteSucursalAsync(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosEmpleado/GetEmpleado", ReplyAction="http://tempuri.org/IServiciosEmpleado/GetEmpleadoResponse")]
        BancoPeru.ProxyEmpleado.EmpleadoBE[] GetEmpleado(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiciosEmpleado/GetEmpleado", ReplyAction="http://tempuri.org/IServiciosEmpleado/GetEmpleadoResponse")]
        System.Threading.Tasks.Task<BancoPeru.ProxyEmpleado.EmpleadoBE[]> GetEmpleadoAsync(string dni);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiciosEmpleadoChannel : BancoPeru.ProxyEmpleado.IServiciosEmpleado, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosEmpleadoClient : System.ServiceModel.ClientBase<BancoPeru.ProxyEmpleado.IServiciosEmpleado>, BancoPeru.ProxyEmpleado.IServiciosEmpleado {
        
        public ServiciosEmpleadoClient() {
        }
        
        public ServiciosEmpleadoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosEmpleadoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosEmpleadoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosEmpleadoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InsertEmpleado(BancoPeru.ProxyEmpleado.EmpleadoBE objCliente) {
            return base.Channel.InsertEmpleado(objCliente);
        }
        
        public System.Threading.Tasks.Task<bool> InsertEmpleadoAsync(BancoPeru.ProxyEmpleado.EmpleadoBE objCliente) {
            return base.Channel.InsertEmpleadoAsync(objCliente);
        }
        
        public BancoPeru.ProxyEmpleado.EmpleadoBE[] GetAllEmpleadoLINQ() {
            return base.Channel.GetAllEmpleadoLINQ();
        }
        
        public System.Threading.Tasks.Task<BancoPeru.ProxyEmpleado.EmpleadoBE[]> GetAllEmpleadoLINQAsync() {
            return base.Channel.GetAllEmpleadoLINQAsync();
        }
        
        public BancoPeru.ProxyEmpleado.EmpleadoBE[] ListarNombresEmpleadoLINQ() {
            return base.Channel.ListarNombresEmpleadoLINQ();
        }
        
        public System.Threading.Tasks.Task<BancoPeru.ProxyEmpleado.EmpleadoBE[]> ListarNombresEmpleadoLINQAsync() {
            return base.Channel.ListarNombresEmpleadoLINQAsync();
        }
        
        public BancoPeru.ProxyEmpleado.EmpleadoBE[] GetClienteSucursal(string dni) {
            return base.Channel.GetClienteSucursal(dni);
        }
        
        public System.Threading.Tasks.Task<BancoPeru.ProxyEmpleado.EmpleadoBE[]> GetClienteSucursalAsync(string dni) {
            return base.Channel.GetClienteSucursalAsync(dni);
        }
        
        public BancoPeru.ProxyEmpleado.EmpleadoBE[] GetEmpleado(string dni) {
            return base.Channel.GetEmpleado(dni);
        }
        
        public System.Threading.Tasks.Task<BancoPeru.ProxyEmpleado.EmpleadoBE[]> GetEmpleadoAsync(string dni) {
            return base.Channel.GetEmpleadoAsync(dni);
        }
    }
}
