//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosBancoPeru
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BancoPeruEntitie : DbContext
    {
        public BancoPeruEntitie()
            : base("name=BancoPeruEntitie")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<CUENTA> CUENTA { get; set; }
        public virtual DbSet<DEPARTAMENTO> DEPARTAMENTO { get; set; }
        public virtual DbSet<DETALLE_PRESTAMO> DETALLE_PRESTAMO { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADO { get; set; }
        public virtual DbSet<PAGO> PAGO { get; set; }
        public virtual DbSet<PRESTAMO> PRESTAMO { get; set; }
        public virtual DbSet<SUCURSAL> SUCURSAL { get; set; }
        public virtual DbSet<EMPLEADOSPORSUCURSAL> EMPLEADOSPORSUCURSAL { get; set; }
        public virtual DbSet<PRESTAMOS> PRESTAMOS { get; set; }
        public virtual DbSet<PUESTOSEMPLEADOS> PUESTOSEMPLEADOS { get; set; }
        public virtual DbSet<vvw_CUENTACLIENTE> vvw_CUENTACLIENTE { get; set; }
        public virtual DbSet<vw_Cliente> vw_Cliente { get; set; }
        public virtual DbSet<vw_EmpleadoDepartamentoSucursal> vw_EmpleadoDepartamentoSucursal { get; set; }
        public virtual DbSet<vw_VistaPagos> vw_VistaPagos { get; set; }
        public virtual DbSet<vw_VistaPrestamos> vw_VistaPrestamos { get; set; }
    
        public virtual ObjectResult<usp_ClienteConsultar_Result> usp_ClienteConsultar(string dniProfesor)
        {
            var dniProfesorParameter = dniProfesor != null ?
                new ObjectParameter("DniProfesor", dniProfesor) :
                new ObjectParameter("DniProfesor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ClienteConsultar_Result>("usp_ClienteConsultar", dniProfesorParameter);
        }
    
        public virtual ObjectResult<usp_CuentaCliente_Result> usp_CuentaCliente(string dni)
        {
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CuentaCliente_Result>("usp_CuentaCliente", dniParameter);
        }
    
        public virtual int usp_DeudaCliente(string dni, ObjectParameter deuda)
        {
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_DeudaCliente", dniParameter, deuda);
        }
    
        public virtual ObjectResult<usp_ListarPrestamosCliente_Result> usp_ListarPrestamosCliente(string dni)
        {
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarPrestamosCliente_Result>("usp_ListarPrestamosCliente", dniParameter);
        }
    
        public virtual ObjectResult<usp_PagosPendientes_Result> usp_PagosPendientes(string dni)
        {
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_PagosPendientes_Result>("usp_PagosPendientes", dniParameter);
        }
    
        public virtual int uspEmpleadoInsertar(string dni_emp, string nom_emp, string ape_emp, string tel_emp, string mail_emp, string dir_emp, Nullable<int> sue_emp, Nullable<System.DateTime> ingreso_emp, Nullable<int> dep_emp)
        {
            var dni_empParameter = dni_emp != null ?
                new ObjectParameter("dni_emp", dni_emp) :
                new ObjectParameter("dni_emp", typeof(string));
    
            var nom_empParameter = nom_emp != null ?
                new ObjectParameter("nom_emp", nom_emp) :
                new ObjectParameter("nom_emp", typeof(string));
    
            var ape_empParameter = ape_emp != null ?
                new ObjectParameter("ape_emp", ape_emp) :
                new ObjectParameter("ape_emp", typeof(string));
    
            var tel_empParameter = tel_emp != null ?
                new ObjectParameter("tel_emp", tel_emp) :
                new ObjectParameter("tel_emp", typeof(string));
    
            var mail_empParameter = mail_emp != null ?
                new ObjectParameter("mail_emp", mail_emp) :
                new ObjectParameter("mail_emp", typeof(string));
    
            var dir_empParameter = dir_emp != null ?
                new ObjectParameter("dir_emp", dir_emp) :
                new ObjectParameter("dir_emp", typeof(string));
    
            var sue_empParameter = sue_emp.HasValue ?
                new ObjectParameter("sue_emp", sue_emp) :
                new ObjectParameter("sue_emp", typeof(int));
    
            var ingreso_empParameter = ingreso_emp.HasValue ?
                new ObjectParameter("ingreso_emp", ingreso_emp) :
                new ObjectParameter("ingreso_emp", typeof(System.DateTime));
    
            var dep_empParameter = dep_emp.HasValue ?
                new ObjectParameter("dep_emp", dep_emp) :
                new ObjectParameter("dep_emp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspEmpleadoInsertar", dni_empParameter, nom_empParameter, ape_empParameter, tel_empParameter, mail_empParameter, dir_empParameter, sue_empParameter, ingreso_empParameter, dep_empParameter);
        }
    
        public virtual int uspPagoEliminar(Nullable<int> id_pago)
        {
            var id_pagoParameter = id_pago.HasValue ?
                new ObjectParameter("id_pago", id_pago) :
                new ObjectParameter("id_pago", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPagoEliminar", id_pagoParameter);
        }
    
        public virtual int uspSucursalActualizar(Nullable<int> id_suc, string nom_suc, string dir_suc, string tel_suc)
        {
            var id_sucParameter = id_suc.HasValue ?
                new ObjectParameter("id_suc", id_suc) :
                new ObjectParameter("id_suc", typeof(int));
    
            var nom_sucParameter = nom_suc != null ?
                new ObjectParameter("nom_suc", nom_suc) :
                new ObjectParameter("nom_suc", typeof(string));
    
            var dir_sucParameter = dir_suc != null ?
                new ObjectParameter("dir_suc", dir_suc) :
                new ObjectParameter("dir_suc", typeof(string));
    
            var tel_sucParameter = tel_suc != null ?
                new ObjectParameter("tel_suc", tel_suc) :
                new ObjectParameter("tel_suc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspSucursalActualizar", id_sucParameter, nom_sucParameter, dir_sucParameter, tel_sucParameter);
        }
    
        public virtual int usp_ClienteActualizar(Nullable<int> idCli, string dNIAlu, string nomCli, string apeCli, string dirCli, string telCli)
        {
            var idCliParameter = idCli.HasValue ?
                new ObjectParameter("IdCli", idCli) :
                new ObjectParameter("IdCli", typeof(int));
    
            var dNIAluParameter = dNIAlu != null ?
                new ObjectParameter("DNIAlu", dNIAlu) :
                new ObjectParameter("DNIAlu", typeof(string));
    
            var nomCliParameter = nomCli != null ?
                new ObjectParameter("NomCli", nomCli) :
                new ObjectParameter("NomCli", typeof(string));
    
            var apeCliParameter = apeCli != null ?
                new ObjectParameter("ApeCli", apeCli) :
                new ObjectParameter("ApeCli", typeof(string));
    
            var dirCliParameter = dirCli != null ?
                new ObjectParameter("DirCli", dirCli) :
                new ObjectParameter("DirCli", typeof(string));
    
            var telCliParameter = telCli != null ?
                new ObjectParameter("TelCli", telCli) :
                new ObjectParameter("TelCli", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ClienteActualizar", idCliParameter, dNIAluParameter, nomCliParameter, apeCliParameter, dirCliParameter, telCliParameter);
        }
    
        public virtual ObjectResult<usp_EmpleadoConsultar_Result> usp_EmpleadoConsultar(string dniEmpleado)
        {
            var dniEmpleadoParameter = dniEmpleado != null ?
                new ObjectParameter("DniEmpleado", dniEmpleado) :
                new ObjectParameter("DniEmpleado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_EmpleadoConsultar_Result>("usp_EmpleadoConsultar", dniEmpleadoParameter);
        }
    
        public virtual ObjectResult<usp_PrestamosCliente_Result> usp_PrestamosCliente(string dni)
        {
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_PrestamosCliente_Result>("usp_PrestamosCliente", dniParameter);
        }
    
        public virtual ObjectResult<usp_ListarPrestamos_Result> usp_ListarPrestamos(string dni)
        {
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarPrestamos_Result>("usp_ListarPrestamos", dniParameter);
        }
    }
}
