//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosBancoPeru
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUENTA
    {
        public int IdCuenta { get; set; }
        public string NroCuenta { get; set; }
        public string Clave { get; set; }
        public int Saldo { get; set; }
        public System.DateTime FechaApertura { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public int IdCliente { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual CLIENTE CLIENTE1 { get; set; }
        public virtual CLIENTE CLIENTE2 { get; set; }
        public virtual CLIENTE CLIENTE3 { get; set; }
        public virtual CLIENTE CLIENTE4 { get; set; }
        public virtual CLIENTE CLIENTE5 { get; set; }
    }
}
