//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosBancoPeru
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_PRESTAMO
    {
        public int IdPrestamo { get; set; }
        public int IdEmpleado { get; set; }
        public string Sucursal { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual EMPLEADO EMPLEADO1 { get; set; }
        public virtual EMPLEADO EMPLEADO2 { get; set; }
        public virtual PRESTAMO PRESTAMO { get; set; }
        public virtual PRESTAMO PRESTAMO1 { get; set; }
        public virtual PRESTAMO PRESTAMO2 { get; set; }
    }
}
