//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosBancoPeru
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_VistaPagos
    {
        public int IdPago { get; set; }
        public int IdPrestamo { get; set; }
        public int IdCliente { get; set; }
        public int ImportePago { get; set; }
        public int NroCuota { get; set; }
        public System.DateTime FechaPago { get; set; }
        public string Nombres { get; set; }
        public string DNICliente { get; set; }
        public string EstadoPago { get; set; }
        public string Estado { get; set; }
    }
}
