//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosBancoPeru
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_VistaPrestamos
    {
        public int IdPrestamo { get; set; }
        public System.DateTime FechaPrestamo { get; set; }
        public int IdCLiente { get; set; }
        public string NombresCliente { get; set; }
        public string DNICliente { get; set; }
        public int Importe { get; set; }
        public Nullable<decimal> Interestotal { get; set; }
        public Nullable<decimal> Importetotal { get; set; }
        public string EstadoPrestamo { get; set; }
        public string Estado { get; set; }
    }
}
